package entity

import (
	"time"

	"github.com/google/uuid"
)

// CaptionStatus tracks whether a caption file is ready for viewers.
type CaptionStatus string

const (
	CaptionStatusPending       CaptionStatus = "pending"
	CaptionStatusAutoGenerated CaptionStatus = "auto_generated"
	CaptionStatusReviewed      CaptionStatus = "reviewed"
	CaptionStatusPublished     CaptionStatus = "published"
)

// CaptionSource indicates whether a caption was auto-generated or manually uploaded.
type CaptionSource string

const (
	CaptionSourceAuto   CaptionSource = "auto"
	CaptionSourceManual CaptionSource = "manual"
)

// Caption holds a subtitle/caption file for a specific language.
type Caption struct {
	ID           uuid.UUID
	VideoID      uuid.UUID
	LanguageCode string
	Format       string // webvtt | srt
	StorageKey   string
	Status       CaptionStatus
	Source       CaptionSource
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// NewCaption creates a new Caption record for a video.
func NewCaption(videoID uuid.UUID, languageCode, format, storageKey string, source CaptionSource) *Caption {
	now := time.Now().UTC()
	status := CaptionStatusPending
	if source == CaptionSourceAuto {
		status = CaptionStatusAutoGenerated
	}
	return &Caption{
		ID:           uuid.New(),
		VideoID:      videoID,
		LanguageCode: languageCode,
		Format:       format,
		StorageKey:   storageKey,
		Status:       status,
		Source:       source,
		CreatedAt:    now,
		UpdatedAt:    now,
	}
}

// MarkPublished transitions a reviewed caption to published.
func (c *Caption) MarkPublished() {
	c.Status = CaptionStatusPublished
	c.UpdatedAt = time.Now().UTC()
}

// MarkReviewed marks the caption as human-reviewed.
func (c *Caption) MarkReviewed() {
	c.Status = CaptionStatusReviewed
	c.UpdatedAt = time.Now().UTC()
}
