package entity

import (
	"time"

	"github.com/google/uuid"
)

// PlaybackSource identifies the surface a playback session started from.
// Values are client-declared, so unknown values are coerced to PlaybackSourceOther
// rather than rejected.
type PlaybackSource string

const (
	PlaybackSourceHome     PlaybackSource = "home"
	PlaybackSourceSearch   PlaybackSource = "search"
	PlaybackSourceSeries   PlaybackSource = "series"
	PlaybackSourceProfile  PlaybackSource = "profile"
	PlaybackSourceLibrary  PlaybackSource = "library"
	PlaybackSourceDirect   PlaybackSource = "direct"
	PlaybackSourceExternal PlaybackSource = "external"
	PlaybackSourceOther    PlaybackSource = "other"
)

// PlaybackPlatform identifies the client platform a playback session ran on.
type PlaybackPlatform string

const (
	PlaybackPlatformWeb       PlaybackPlatform = "web"
	PlaybackPlatformIOS       PlaybackPlatform = "ios"
	PlaybackPlatformAndroid   PlaybackPlatform = "android"
	PlaybackPlatformTVOS      PlaybackPlatform = "tvos"
	PlaybackPlatformAndroidTV PlaybackPlatform = "android_tv"
	PlaybackPlatformOther     PlaybackPlatform = "other"
)

// RetentionBuckets is the number of per-video position buckets tracked for
// retention curves (one per percent of duration).
const RetentionBuckets = 100

// NormalizePlaybackSource coerces a client-declared source to a known value,
// falling back to PlaybackSourceOther.
func NormalizePlaybackSource(raw string) PlaybackSource {
	switch PlaybackSource(raw) {
	case PlaybackSourceHome, PlaybackSourceSearch, PlaybackSourceSeries,
		PlaybackSourceProfile, PlaybackSourceLibrary, PlaybackSourceDirect,
		PlaybackSourceExternal:
		return PlaybackSource(raw)
	default:
		return PlaybackSourceOther
	}
}

// NormalizePlaybackPlatform coerces a client-declared platform to a known value,
// falling back to PlaybackPlatformOther.
func NormalizePlaybackPlatform(raw string) PlaybackPlatform {
	switch PlaybackPlatform(raw) {
	case PlaybackPlatformWeb, PlaybackPlatformIOS, PlaybackPlatformAndroid,
		PlaybackPlatformTVOS, PlaybackPlatformAndroidTV:
		return PlaybackPlatform(raw)
	default:
		return PlaybackPlatformOther
	}
}

// ViewThresholdSeconds returns the cumulative watched seconds at which a
// playback session counts as a view: 30 seconds, or half the video for
// content shorter than a minute, with a floor of 1 second.
func ViewThresholdSeconds(durationSeconds int64) int64 {
	half := durationSeconds / 2
	if half < 1 {
		half = 1
	}
	if half < 30 {
		return half
	}
	return 30
}

// PlaybackSession is one view session of a video, accumulated from client
// heartbeats. The ID is generated by the client so heartbeats are idempotent.
type PlaybackSession struct {
	ID             uuid.UUID
	VideoID        uuid.UUID
	UserID         *uuid.UUID
	Source         PlaybackSource
	Platform       PlaybackPlatform
	CountryCode    string
	StartedAt      time.Time
	LastEventAt    time.Time
	LastPosition   int64
	MaxPosition    int64
	WatchedSeconds int64
	WatchedBuckets []int
	IsView         bool
	Completed      bool
}
